name: "Run unit tests with Vitest"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: "Install NPM dependencies"
        run: npm install
      - name: "Test with Vitest"
        run: npx vitest run
